In [1]:
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
!ls "/content/drive/My Drive/Deep Learning"

 1.jpg			  fashion-mnist_train.csv   Untitled4.ipynb
 2.jpg			  Housing.CSV		    Untitled5.ipynb
 3.jpg			  insurance.csv		    Untitled6.ipynb
'Assignment #4.ipynb'	  Untitled		    Untitled7.ipynb
'Assignment #5.ipynb'	  Untitled0.ipynb	    Untitled8.ipynb
 cifar-10-batches-py	  Untitled1.ipynb	    Untitled9.ipynb
 creditcard.csv		  Untitled2.ipynb	    win2.xls
 fashion-mnist_test.csv   Untitled3.ipynb	    wine1.xls


In [4]:
import os
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import torch.optim as optim
import numpy as np
from sklearn.metrics import accuracy_score

In [18]:
dataset = pd.read_csv("/content/drive/My Drive/Deep Learning/creditcard.csv")

In [19]:
dataset.head()

Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [20]:
from sklearn.preprocessing import StandardScaler
sclaer = StandardScaler()

In [21]:
X_data = dataset.iloc[:,0:-1].values
X_data[0:2]

array([[ 0.00000000e+00, -1.35980713e+00, -7.27811733e-02,
         2.53634674e+00,  1.37815522e+00, -3.38320770e-01,
         4.62387778e-01,  2.39598554e-01,  9.86979013e-02,
         3.63786970e-01,  9.07941720e-02, -5.51599533e-01,
        -6.17800856e-01, -9.91389847e-01, -3.11169354e-01,
         1.46817697e+00, -4.70400525e-01,  2.07971242e-01,
         2.57905802e-02,  4.03992960e-01,  2.51412098e-01,
        -1.83067779e-02,  2.77837576e-01, -1.10473910e-01,
         6.69280749e-02,  1.28539358e-01, -1.89114844e-01,
         1.33558377e-01, -2.10530535e-02,  1.49620000e+02],
       [ 0.00000000e+00,  1.19185711e+00,  2.66150712e-01,
         1.66480113e-01,  4.48154078e-01,  6.00176493e-02,
        -8.23608088e-02, -7.88029833e-02,  8.51016549e-02,
        -2.55425128e-01, -1.66974414e-01,  1.61272666e+00,
         1.06523531e+00,  4.89095016e-01, -1.43772296e-01,
         6.35558093e-01,  4.63917041e-01, -1.14804663e-01,
        -1.83361270e-01, -1.45783041e-01, -6.90831352e-

In [22]:
Y_data = dataset.iloc[:,-1].values
Y_data[0:5]

array([0, 0, 0, 0, 0])

In [23]:
unique , counts = np.unique(Y_data,return_counts = True)
print(unique,counts)

[0 1] [284315    492]


In [24]:
X_data = sclaer.fit_transform(X_data)
X_data[0:2]

array([[-1.99658302, -0.69424232, -0.04407492,  1.6727735 ,  0.97336551,
        -0.24511658,  0.34706795,  0.19367894,  0.08263728,  0.33112778,
         0.08338555, -0.54040704, -0.61829572, -0.99609892, -0.32461019,
         1.60401384, -0.53683287,  0.24486345,  0.03076993,  0.49628203,
         0.32611802, -0.02492336,  0.38285444, -0.17691133,  0.11050692,
         0.24658544, -0.39217043,  0.33089162, -0.06378115,  0.24496426],
       [-1.99658302,  0.60849633,  0.16117592,  0.1097971 ,  0.31652293,
         0.04348335, -0.06181997, -0.06370021,  0.07125348, -0.23249419,
        -0.15334963,  1.58000285,  1.06608857,  0.4914182 , -0.14998248,
         0.69436042,  0.52943375, -0.13516997, -0.21876258, -0.17908605,
        -0.08961086, -0.3073768 , -0.88007675,  0.16220118, -0.56113055,
         0.3206939 ,  0.26106948, -0.02225568,  0.04460752, -0.34247454]])

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X_data,Y_data,test_size=0.3)

In [26]:
from keras.models import Sequential
from keras.layers import Dense

In [27]:
classifier = Sequential()
classifier.add(Dense(40 , input_dim = 30 , activation = 'relu'))
classifier.add(Dense(30 , input_dim = 40 , activation = 'relu'))
classifier.add(Dense(20 , input_dim = 30 , activation = 'relu'))
classifier.add(Dense(10 , input_dim = 20 , activation = 'relu'))
classifier.add(Dense(6 , input_dim = 10 , activation = 'relu'))
classifier.add(Dense(4 , input_dim = 6 , activation = 'relu'))
classifier.add(Dense(1, input_dim = 4 , activation = 'sigmoid'))

In [28]:
classifier.compile(loss = 'binary_crossentropy' , optimizer = 'adam' , metrics = ['accuracy'] )

In [29]:
classifier.fit( x_train , y_train , epochs = 200 , batch_size = 500 )

Epoch 1/200
399/399 [==============================] - 1s 2ms/step - loss: 0.6057 - accuracy: 0.9651
Epoch 2/200
399/399 [==============================] - 1s 2ms/step - loss: 0.4558 - accuracy: 0.9993
Epoch 3/200
399/399 [==============================] - 1s 2ms/step - loss: 0.3481 - accuracy: 0.9994
Epoch 4/200
399/399 [==============================] - 1s 2ms/step - loss: 0.2695 - accuracy: 0.9994
Epoch 5/200
399/399 [==============================] - 1s 2ms/step - loss: 0.2116 - accuracy: 0.9994
Epoch 6/200
399/399 [==============================] - 1s 2ms/step - loss: 0.1682 - accuracy: 0.9994
Epoch 7/200
399/399 [==============================] - 1s 2ms/step - loss: 0.1353 - accuracy: 0.9994
Epoch 8/200
399/399 [==============================] - 1s 3ms/step - loss: 0.1099 - accuracy: 0.9994
Epoch 9/200
399/399 [==============================] - 1s 2ms/step - loss: 0.0899 - accuracy: 0.9994
Epoch 10/200
399/399 [==============================] - 1s 2ms/step - loss: 0.0742 - accura

In [30]:
classifier.evaluate(x_test,y_test)

2671/2671 [==============================] - 2s 861us/step - loss: 0.0037 - accuracy: 0.9995


[0.0037326994352042675, 0.9995201230049133]