Assignment set 3 by [Pegah Khazaei](https://github.com/pegahkhazaeii/Deep_Learning_F20_Assignments/), September 28, 2020

In [20]:
import torch
import numpy as np

Create three random tensors, including a 3 * 3 tensor as float, a 4 * 4 tensor as double, and a 5 * 3 * 4 tensor as short type

In [21]:
A = torch.randn(3,3, dtype=torch.float)
A

tensor([[ 0.6864,  0.2657, -0.2326],
        [ 0.7944,  0.5242,  0.3279],
        [ 0.7854, -0.1764, -0.1975]])

In [22]:
B = torch.randn(4,4, dtype=torch.double)
B

tensor([[-0.0616, -0.8535, -1.3463, -0.2824],
        [-1.1061, -0.5148, -0.1858,  1.7297],
        [ 0.6775,  0.1165, -0.7906, -0.3312],
        [-0.6021, -0.5338,  1.0570, -0.2093]], dtype=torch.float64)

In [23]:
C = torch.randint(0, 100, (5, 3, 4), dtype=torch.short)
C

tensor([[[61, 61, 91, 42],
         [46, 45, 16, 58],
         [13, 37, 38, 66]],

        [[14, 34, 59,  8],
         [15, 42, 12, 71],
         [77, 17,  5, 89]],

        [[56, 89, 61, 74],
         [23, 77, 89, 34],
         [ 4, 70, 81,  0]],

        [[26, 10, 32, 11],
         [82, 90, 64, 21],
         [89,  5, 51, 44]],

        [[41, 83, 81, 75],
         [63, 56, 76, 51],
         [65, 28,  1, 53]]], dtype=torch.int16)

Change their elements in the GPU




In [24]:
A_gpu = A.to(device='cuda')
A_gpu

tensor([[ 0.6864,  0.2657, -0.2326],
        [ 0.7944,  0.5242,  0.3279],
        [ 0.7854, -0.1764, -0.1975]], device='cuda:0')

In [25]:
A_gpu = A_gpu * 2
A_gpu

tensor([[ 1.3728,  0.5314, -0.4652],
        [ 1.5889,  1.0485,  0.6557],
        [ 1.5707, -0.3529, -0.3949]], device='cuda:0')

In [26]:
B_gpu = B.to(device='cuda')
B_gpu

tensor([[-0.0616, -0.8535, -1.3463, -0.2824],
        [-1.1061, -0.5148, -0.1858,  1.7297],
        [ 0.6775,  0.1165, -0.7906, -0.3312],
        [-0.6021, -0.5338,  1.0570, -0.2093]], device='cuda:0',
       dtype=torch.float64)

In [27]:
B_gpu = B_gpu + 3
B_gpu

tensor([[2.9384, 2.1465, 1.6537, 2.7176],
        [1.8939, 2.4852, 2.8142, 4.7297],
        [3.6775, 3.1165, 2.2094, 2.6688],
        [2.3979, 2.4662, 4.0570, 2.7907]], device='cuda:0',
       dtype=torch.float64)

In [28]:
C_gpu = C.to(device='cuda')
C_gpu

tensor([[[61, 61, 91, 42],
         [46, 45, 16, 58],
         [13, 37, 38, 66]],

        [[14, 34, 59,  8],
         [15, 42, 12, 71],
         [77, 17,  5, 89]],

        [[56, 89, 61, 74],
         [23, 77, 89, 34],
         [ 4, 70, 81,  0]],

        [[26, 10, 32, 11],
         [82, 90, 64, 21],
         [89,  5, 51, 44]],

        [[41, 83, 81, 75],
         [63, 56, 76, 51],
         [65, 28,  1, 53]]], device='cuda:0', dtype=torch.int16)

In [29]:
C_gpu = C_gpu - 5
C_gpu

tensor([[[56, 56, 86, 37],
         [41, 40, 11, 53],
         [ 8, 32, 33, 61]],

        [[ 9, 29, 54,  3],
         [10, 37,  7, 66],
         [72, 12,  0, 84]],

        [[51, 84, 56, 69],
         [18, 72, 84, 29],
         [-1, 65, 76, -5]],

        [[21,  5, 27,  6],
         [77, 85, 59, 16],
         [84,  0, 46, 39]],

        [[36, 78, 76, 70],
         [58, 51, 71, 46],
         [60, 23, -4, 48]]], device='cuda:0', dtype=torch.int16)

Display the order of its elements and its transpose in the memory then use storage offset and contiguous

Display A ( 3 * 3 tensor as float) and its transpose use storage

In [30]:
A_t=A.t()
A_t

tensor([[ 0.6864,  0.7944,  0.7854],
        [ 0.2657,  0.5242, -0.1764],
        [-0.2326,  0.3279, -0.1975]])

In [31]:
print(A.storage())

 0.6863815188407898
 0.2656787633895874
 -0.23260080814361572
 0.7944348454475403
 0.5242291688919067
 0.3278549611568451
 0.7853590846061707
 -0.1764255166053772
 -0.1974695771932602
[torch.FloatStorage of size 9]


In [32]:
print(A_t.storage())

 0.6863815188407898
 0.2656787633895874
 -0.23260080814361572
 0.7944348454475403
 0.5242291688919067
 0.3278549611568451
 0.7853590846061707
 -0.1764255166053772
 -0.1974695771932602
[torch.FloatStorage of size 9]


Display A ( 3 * 3 tensor as float) in the memory and its transpose use storage_offse

In [33]:
print(A.storage_offset())

0


In [34]:
print(A_t.storage_offset())

0


Display A (3 * 3 tensor as float) in the memory and its transpose use contiguous

In [35]:
print(A.contiguous())

tensor([[ 0.6864,  0.2657, -0.2326],
        [ 0.7944,  0.5242,  0.3279],
        [ 0.7854, -0.1764, -0.1975]])


In [36]:
print(A_t.contiguous())

tensor([[ 0.6864,  0.7944,  0.7854],
        [ 0.2657,  0.5242, -0.1764],
        [-0.2326,  0.3279, -0.1975]])


##### Display B (4 * 4 tensor as double) and its transpose use storage

In [37]:
B_t=B.t()
B_t

tensor([[-0.0616, -1.1061,  0.6775, -0.6021],
        [-0.8535, -0.5148,  0.1165, -0.5338],
        [-1.3463, -0.1858, -0.7906,  1.0570],
        [-0.2824,  1.7297, -0.3312, -0.2093]], dtype=torch.float64)

In [38]:
B.stride()

(4, 1)

In [39]:
B_t.stride()

(1, 4)

In [40]:
print(B.storage())

 -0.06157679210283572
 -0.8535091127623161
 -1.3463335528003266
 -0.28243708563876685
 -1.106137933965504
 -0.5148291567400507
 -0.18578877819413792
 1.729652934819689
 0.6775199586190435
 0.11645251515736678
 -0.7906398525475277
 -0.33119272322058146
 -0.6020525049525334
 -0.533752693341385
 1.0570290919537308
 -0.20925632604091304
[torch.DoubleStorage of size 16]


In [41]:
print(B_t.storage())

 -0.06157679210283572
 -0.8535091127623161
 -1.3463335528003266
 -0.28243708563876685
 -1.106137933965504
 -0.5148291567400507
 -0.18578877819413792
 1.729652934819689
 0.6775199586190435
 0.11645251515736678
 -0.7906398525475277
 -0.33119272322058146
 -0.6020525049525334
 -0.533752693341385
 1.0570290919537308
 -0.20925632604091304
[torch.DoubleStorage of size 16]


Display B ( 4 * 4 tensor as double)  in the memory and its transpose use storage_offset

In [42]:
print(B.storage_offset())

0


In [43]:
print(B_t.storage_offset())

0


Display B (4 * 4 tensor as double)  in the memory and its transpose use contiguous

In [44]:
print(B.contiguous())

tensor([[-0.0616, -0.8535, -1.3463, -0.2824],
        [-1.1061, -0.5148, -0.1858,  1.7297],
        [ 0.6775,  0.1165, -0.7906, -0.3312],
        [-0.6021, -0.5338,  1.0570, -0.2093]], dtype=torch.float64)


In [45]:
print(B_t.contiguous())

tensor([[-0.0616, -1.1061,  0.6775, -0.6021],
        [-0.8535, -0.5148,  0.1165, -0.5338],
        [-1.3463, -0.1858, -0.7906,  1.0570],
        [-0.2824,  1.7297, -0.3312, -0.2093]], dtype=torch.float64)


Display C (5 * 3 * 4 tensor as short type) in the memory and its transpose use storage

In [46]:
C_t=C.transpose(1,0)
C_t

tensor([[[61, 61, 91, 42],
         [14, 34, 59,  8],
         [56, 89, 61, 74],
         [26, 10, 32, 11],
         [41, 83, 81, 75]],

        [[46, 45, 16, 58],
         [15, 42, 12, 71],
         [23, 77, 89, 34],
         [82, 90, 64, 21],
         [63, 56, 76, 51]],

        [[13, 37, 38, 66],
         [77, 17,  5, 89],
         [ 4, 70, 81,  0],
         [89,  5, 51, 44],
         [65, 28,  1, 53]]], dtype=torch.int16)

In [47]:
print(C.storage())

 61
 61
 91
 42
 46
 45
 16
 58
 13
 37
 38
 66
 14
 34
 59
 8
 15
 42
 12
 71
 77
 17
 5
 89
 56
 89
 61
 74
 23
 77
 89
 34
 4
 70
 81
 0
 26
 10
 32
 11
 82
 90
 64
 21
 89
 5
 51
 44
 41
 83
 81
 75
 63
 56
 76
 51
 65
 28
 1
 53
[torch.ShortStorage of size 60]


In [48]:
print(C_t.storage())

 61
 61
 91
 42
 46
 45
 16
 58
 13
 37
 38
 66
 14
 34
 59
 8
 15
 42
 12
 71
 77
 17
 5
 89
 56
 89
 61
 74
 23
 77
 89
 34
 4
 70
 81
 0
 26
 10
 32
 11
 82
 90
 64
 21
 89
 5
 51
 44
 41
 83
 81
 75
 63
 56
 76
 51
 65
 28
 1
 53
[torch.ShortStorage of size 60]


Display C (5 * 3 * 4 tensor as short type) in the memory and its transpose use storage_offset

In [70]:
print(C.storage_offset())

0


In [71]:
print(C_t.storage_offset())

0


Display C (5 * 3 * 4 tensor as short type) in the memory and its transpose use contiguous

In [72]:
print(C.contiguous())

tensor([[[78, 43, 15, 99],
         [80, 44, 82, 90],
         [89, 91, 95, 88]],

        [[47, 96,  8, 41],
         [ 5, 74, 28, 20],
         [94,  0, 89, 22]],

        [[15, 45, 84, 91],
         [18, 75, 81, 93],
         [49, 28, 34, 81]],

        [[86, 77, 95, 13],
         [25, 28,  9, 54],
         [49, 11, 81, 43]],

        [[ 4, 93, 31, 23],
         [ 1, 46, 32, 31],
         [42, 79, 23, 35]]], dtype=torch.int16)


In [73]:
print(C_t.contiguous())

tensor([[[78, 43, 15, 99],
         [47, 96,  8, 41],
         [15, 45, 84, 91],
         [86, 77, 95, 13],
         [ 4, 93, 31, 23]],

        [[80, 44, 82, 90],
         [ 5, 74, 28, 20],
         [18, 75, 81, 93],
         [25, 28,  9, 54],
         [ 1, 46, 32, 31]],

        [[89, 91, 95, 88],
         [94,  0, 89, 22],
         [49, 28, 34, 81],
         [49, 11, 81, 43],
         [42, 79, 23, 35]]], dtype=torch.int16)


##### Save and load one among the elements of tensors using the torch and the h5py file

In [11]:
import h5py

In [22]:
f = h5py.File('./myHdf5.h5', 'w')
dset = f.create_dataset('coords', data=A.numpy())
f.close()

In [23]:
f = h5py.File('float_tensor.hdf5', 'w')
dset = f.create_dataset('coords', data=A.numpy())
f.close()


In [24]:
f

<Closed HDF5 file>

In [25]:
dset

<Closed HDF5 dataset>

In [26]:
f = h5py.File('float_tensor.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

##### Show the different true and false requires_grad values in Autograd by the backward method

In [17]:
a = torch.rand((3,3))
b = torch.ones((3,3),requires_grad=True)
c = torch.zeros((3,3))

In [18]:
x = a + b
x.requires_grad

True

In [19]:
y=a+c

In [15]:
b.requires_grad

False

In [31]:
x.grad is None

True

In [49]:
T1 = torch.tensor([[5,3,1],[2,5,1]], dtype=torch.float, requires_grad=True)
T2 = torch.zeros(2,3)
T1_T2 = (T1+T2*5).sum()

In [50]:
T1_T2.backward()

print(T1_T2)

T1.grad

tensor(17., grad_fn=<SumBackward0>)


tensor([[1., 1., 1.],
        [1., 1., 1.]])